### ISSUE TITLE
Broken Pipe while installing extension

### ISSUE THREAD

**Issue by np24** [fablabnbg/inkscape-silhouette#104] opened 2020-06-13 02:11 UTC
While i am trying to install the silhouette extension, this error is generated

 sudo dpkg -i inkscape-silhouette_1.22-1_all.deb
(Reading database ... 289348 files and directories currently installed.)
Preparing to unpack inkscape-silhouette_1.22-1_all.deb ...
Unpacking inkscape-silhouette (1.22-1) ...
dpkg: error processing archive inkscape-silhouette_1.22-1_all.deb (--install):
 trying to overwrite '/usr/share/inkscape/extensions/setup.py', which is also in package inkscape 1.0+r73+1~ubuntu18.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 inkscape-silhouette_1.22-1_all.deb

I'm running linux mint 19.3
Any help would be greatly appreciated. I had this working at one point and managed to break it while doing an update. I even went to the extreme and reinstalled linux just to see if that would fix it.
Thanks

**Comment by t0b3** [comment] 2020-06-13 06:42
look like duplicate of #100: setup.py should not be included in deb

**Closed as completed** 2020-12-31 17:09 UTC
