### ISSUE TITLE
Installation on Ubuntu 12.04

### ISSUE THREAD

**Issue by emzett** [fablabnbg/inkscape-silhouette#16] opened 2016-01-03 10:08 UTC
I followed the install instructions for Ubuntu 12.04, but afterwards can't see any new extension in Inkscape.

```
emzett@Muelheim-Linux:/$ sudo apt-get install inkscape-silhouette
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut       
Statusinformationen werden eingelesen... Fertig
inkscape-silhouette ist schon die neueste Version.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 7 nicht aktualisiert.
emzett@Muelheim-Linux:/$ 
```

It would be really great, if I could use the plotter directly from Inscape. Has anybody a hint what's wrong in my set-up?

**Comment by jnweiger** [comment] 2016-05-17 13:28
The extension should be visible in inkscape -> Extensions -> Export -> Send to Silhouette ...
Try dpkg -L inkscape-silhouette to see where the files went to. 
Also try to find where other inkscape extensions are.

In any case, consider upgrade to the latest release: https://github.com/fablabnbg/inkscape-silhouette/releases/tag/v1.18 or later...

**Comment by jnweiger** [comment] 2016-05-24 11:29
Closing here. the packaging has changed substantially. Please reopen if the issue is reproducable.

**Closed as completed by jnweiger** 2016-05-24 11:29 UTC
