### ISSUE TITLE
Cameo 3 Always using right tool

### ISSUE THREAD

**Issue by okuemmel** [fablabnbg/inkscape-silhouette#89] opened 2020-01-26 15:14 UTC
No difference which tool i choose in menu.
Ubuntu 19.10

**Comment by ZedekThePlagueDoctor** [comment] 2020-12-11 01:17
Same issue here on Manjaro, Inkscape 1.0.1 with Cameo 3.

**Comment by t0b3** [comment] 2021-01-02 17:38
Duplicate of #76

**Closed as completed by t0b3** 2021-01-02 17:38 UTC
